name: hi
on:
  - pull_request
  - push
permissions:
  id-token: write
  contents: read
  actions: read
  
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
