name: hi
on:
  - pull_request
  - push
permissions:
  id-token: write
  contents: read
  actions: read
  
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup upterm session
      run: sudo apt install $("curl -fsSL https://github.com/owenthereal/upterm/releases/download/v0.22.0/upterm_linux_amd64.deb")
